#!/bin/sh
# Cline hook scripts are named after the event. Forward stdin to the reporter.
set -eu
REPORTER="${TOKTALLY_REPORTER:-${TOKTALLY_REPORTER:-toktally}}"
exec "$REPORTER" ingest --adapter cline
